### ISSUE TITLE
glColor4ub and glLineWidth don't work

### ISSUE THREAD

**Issue by Koalar** [Microsoft/WinObjC#2777]
I'm migrating one of my iOS app which is based on cocos2d v1.  Most of it runs like a charm when compiled with WinObjC.  But I noticed that glColor4ub and glLineWidth don't work.  When drawing a line on a texture it always gives white line with thickness of 1 pixel no matter what color I set in glColor4ub and how wide I set in glLineWidth.  Is there any work around for these 2 APIs?

**Comment by DHowett-MSFT** [comment]
That definitely shouldn't be. Can you share a minimal repro project that recapitulates this behavior?

Thanks!

**Comment by Koalar** [comment]
Code snip is as below:

                CCRenderTexture *texArrow = [CCRenderTexture renderTextureWithWidth:32 height:drawVectorLen];
                [texTrackVector begin];
                glLineWidth(2);
                glColor4ub(0, 255, 255, 255);
                ccDrawLine(ccp(8.5, 0), ccp(0, 8));
                ccDrawLine(ccp(8.5, 0), ccp(17, 8));
                ccDrawLine(ccp(8.5, 0), ccp(8.5, drawVectorLen));
                glLineWidth(1);
                glColor4ub(255, 255, 255, 255);
                [texArrow end];

I noticed that in file OpenGLES20Context.mm function glColor4ub is not implemented.  Function glColor4f seems to be implemented but doesn't work neither.  Same thing happens with glLineWidth.

**Comment by Koalar** [comment]
Any suggestions?

**Comment by edvv** [comment]
@Koalar This may explain some issues:

https://stackoverflow.com/questions/9794508/glcolor4ub-in-opengl-es-2-0

https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/OpenGLESontheiPhone/OpenGLESontheiPhone.html

states:

OpenGL ES 2.0 is the baseline profile for iOS devices, featuring a configurable graphics pipeline based on programmable shaders.

**Comment by Koalar** [comment]
I'm still waiting for answers.  It seems that WinObjC does not fully support OpenGL ES 1.1.  But everything else is running pretty good.  I really wanna succeed this.  Any help?

**Comment by DHowett-MSFT** [comment]
Hi @Koalar. I dug through our GL implementation, and it looks like we don't implement glColor4ub; @edvv is right that we target OpenGLES 2.0.

It's possible that iOS offers some limited backwards compatibility for 1.1. If you can migrate to glColor4f, that'd be a pretty quick solution.

Right now, our implementation of `glColor4ub` is:

```c
void OpenGLES20Context::glColor4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha) {
    LOG_MESSAGE(__FILE__, __LINE__, "ERROR: Not implemented.");
}
```

Now, as for `glLineWidth`: I can't find anything we've done that should cause that to not work. In fact, we're just re-exporting the function from [ANGLE](https://github.com/google/angle), the OpenGLES->Direct2D adapter we consume. It may be worth chasing down a bug on their end, as it may be a known regression or fixed in a newer version.

**Comment by Koalar** [comment]
Ok, unfortunately, glColor4f doesn't work neither.  I tried that before I posted this issue.  It seems  implemented but doesn't work.  Otherwise it will be pretty easy to make my own glCorlor4ub from glColor4f.  To make it work, it used glColorPointer as a work around.  But I found it too slow when there are plenty to draw which is not acceptable.  And still don't have a way to change the line width.  Everything else works pretty fine.  But this seems to be a dead end.  Pretty frustrated.

**Comment by edvv** [comment]
See:

https://stackoverflow.com/questions/18449709/is-there-and-alternatice-for-gllinewidth-in-opengl-es-2-0

In general, I think you will find that one needs to use polygons and shaders and accept many limitations unless you want to start writing a lot of OpenGL code. OpenGL is good for some things, but not great for other things. As a reference, you may wish to google  QuartzGL:

https://en.wikipedia.org/wiki/Quartz_Compositor#QuartzGL

I can't get into the details of the limitations because of NDA issues.

**Comment by Koalar** [comment]
Thanks.  I know nothing about OpenGL.  Finally I got work arounds for the both.  I use glColorPointer instead of glColor4ub.  I was making a mistake that the program runs into a really wrong loop which take a lot of time.  After I corrected it, the time consuming of glColorPointer is acceptable.  For glLineWidth, I draw rectangles for straight lines which are wider than 1px and convert other holo shape drawings(circle, arc, dash line, etc.) into line drawings.  They are working fine now.
